'use strict';import{syslog}from'./syslog.js';import{localert}from'./locmodals.js';import{store as lstore}from'./localStorage.js';import{Prefix}from'./ntools.js';const list=document.querySelector('section#content div ul');list||syslog.panic(Error('Ausgabeliste fehlt!'));const dom2prefix=new Map,ntoahex=(a)=>{try{if(!Number.isSafeInteger(a)||a!=a>>>0)throw Error(`ntoahex: Adresse unzulässig? ${a}`);let b=a.toString(16);return b=Array(9-b.length).join('0')+b,`0x${b}`}catch(a){return syslog.error(a),null}},buildElement=(a)=>{try{if(!(a instanceof Prefix))throw Error('Kein Prefix Objekt!');const b=a.asStrings(),c=`
      <p>
        <span class="ui-state-highlight">${b.source}</span>
        <span class="ui-state-highlight">${b.lower} &ndash; ${b.upper}</span>
      </p>
      <p>
        <span>${b.mask}</span>
        <span>${ntoahex(a.lower)} &ndash; ${ntoahex(a.upper)}</span>
      </p>
    `,d=document.createElement('li');return d.innerHTML=c,d}catch(a){return syslog.error(a),null}},overlap=()=>{try{const a=[...list.children].sort((c,a)=>dom2prefix.get(c).len-dom2prefix.get(a).len),b=a.length;a.forEach((a,b)=>{const c=dom2prefix.get(a);if(!c)throw Error(`dom2prefix: ${b}. Element nicht gefunden`);c.overlapInfo='',[...a.querySelectorAll('p.ui-state-error')].forEach((a)=>{a.remove()})});for(let c=0;c<b;++c){const d=dom2prefix.get(a[c]);for(let e=c+1;e<b;++e){const b=dom2prefix.get(a[e]);if(d.is(b))throw Error(`Duplikate: ${d.source}, ${b.source}`);d.contains(b)&&(d.overlapInfo+=`<p class="ui-state-error"><span>enthält</span><span>${b.source}</span></p>`,b.overlapInfo+=`<p class="ui-state-error"><span>enthalten in</span><span>${d.source}</span></p>`)}}a.forEach((a)=>{const b=dom2prefix.get(a);a.insertAdjacentHTML('beforeend',b.overlapInfo||''),delete b.overlapInfo})}catch(a){return syslog.panic(a),-1}},store=()=>{let a=[];try{[...list.children].forEach((b)=>{a.push(dom2prefix.get(b).source)}),lstore('prefixes',a)}catch(a){return void syslog.error(a)}},addPrefix=(a)=>{try{const b=new Prefix(a);[...list.children].forEach((a)=>{const c=dom2prefix.get(a);if(b.is(c)){const a=`Adressbereich existiert bereits: ${c.source}`;throw localert(a),Error(a)}});const c=buildElement(b);if(!c)throw Error('addPrefix caller');list.appendChild(c),dom2prefix.set(c,b)}catch(a){return syslog.error(a),-1}return 0},input=document.querySelector('#input-prefix');input||syslog.panic(Error('HTML unvollst\xE4ndig?')),input.addEventListener('change',function(){const a=(input.value||'').replace('#','/').trim();if(!a)return void localert('Bitte ein Pr\xE4fix eingeben.');input.blur();const b=addPrefix(a);if(!b)return overlap(),void store()}),list.addEventListener('delete',function(a){if(a.stopPropagation(),a.preventDefault(),a.detail&&a.detail.closest){const b=a.detail.closest;b.remove(),dom2prefix.delete(b),overlap(),store()}}),document.querySelector('body').addEventListener('clear',function(){list.innerHTML='',dom2prefix.clear(),lstore('prefixes',[])});try{const a=lstore('prefixes')||[],b=a.every((a)=>!addPrefix(a));if(!b)throw Error('Fehler beim Laden aus localStorage');overlap()}catch(a){syslog.error(a)}